"""
AMBER / HiRRIXS — bluesky RE Manager startup script.
Auto-generated by devices.py — edit as needed before production use.
"""
from ophyd import EpicsMotor, EpicsSignalRO, Device
from ophyd.sim import SynGauss, SynAxis
from ophyd import Component as Cpt
from ophyd.status import DeviceStatus
import bluesky.plans as bp
import bluesky.plan_stubs as bps
import threading
import time as _time
import numpy as _np


# ── AveragedScalar ───────────────────────────────────────────────────
# Reads an AI PV at 50 ms intervals over exposure_time seconds and
# returns the mean.  Fully compatible with bluesky plans — the RE
# waits for trigger() to complete before moving to the next point,
# so the motor is always stationary during acquisition.

class AveragedScalar(Device):
    """Time-averaging scalar detector for analog signals.

    Samples the PV every 50 ms for `exposure_time` seconds and reports
    the mean, standard deviation, and sample count.  The `exposure_time`
    attribute is set at runtime by the custom plan wrappers in 15_plans.py.
    """
    raw = Cpt(EpicsSignalRO, "")

    def __init__(self, *args, exposure_time: float = 1.0, **kwargs):
        super().__init__(*args, **kwargs)
        self.exposure_time = exposure_time
        self._mean  = float("nan")
        self._std   = float("nan")
        self._count = 0

    def trigger(self):
        status = DeviceStatus(self)

        def _acquire():
            samples = []
            t0 = _time.monotonic()
            while _time.monotonic() - t0 < self.exposure_time:
                v = self.raw.get()
                if v is not None:
                    samples.append(float(v))
                _time.sleep(0.05)
            if samples:
                self._mean  = float(_np.mean(samples))
                self._std   = float(_np.std(samples))
                self._count = len(samples)
            else:
                self._mean = self._std = float("nan")
                self._count = 0
            status.set_finished()

        threading.Thread(target=_acquire, daemon=True).start()
        return status

    def read(self):
        ts = _time.time()
        return {
            self.name:           {"value": self._mean,  "timestamp": ts},
            self.name + "_std":  {"value": self._std,   "timestamp": ts},
            self.name + "_n":    {"value": self._count, "timestamp": ts},
        }

    def describe(self):
        src = self.raw.pvname
        return {
            self.name:           {"source": src, "dtype": "number", "shape": []},
            self.name + "_std":  {"source": src, "dtype": "number", "shape": []},
            self.name + "_n":    {"source": src, "dtype": "number", "shape": []},
        }

# ── Motors ──────────────────────────────────────────────────────────
ap131pos = EpicsMotor("BL0601:AP131Pos", name="ap131pos", labels={"motors"})  # AP131Pos
ap131size = EpicsMotor("BL0601:AP131Size", name="ap131size", labels={"motors"})  # AP131Size
ap132pos = EpicsMotor("BL0601:AP132Pos", name="ap132pos", labels={"motors"})  # AP132Pos
ap132size = EpicsMotor("BL0601:AP132Size", name="ap132size", labels={"motors"})  # AP132Size
beamlineenergy = EpicsMotor("BL6013:BeamlineEnergyUDP", name="beamlineenergy", labels={"motors"})  # BeamlineEnergy
diag101 = EpicsMotor("BL0601:DIAG101Pos", name="diag101", labels={"motors"})  # DIAG101
diag132 = EpicsMotor("BL0601:DIAG132Insert", name="diag132", labels={"motors"})  # DIAG132
diag133 = EpicsMotor("BL6013:DIAG133Insert", name="diag133", labels={"motors"})  # DIAG133
diag134 = EpicsMotor("BL6013:DIAG134Insert", name="diag134", labels={"motors"})  # DIAG134
detectorx = EpicsMotor("BL6013:DetectorX", name="detectorx", labels={"motors"})  # DetectorX
detectorz = EpicsMotor("BL6013:DetectorZ", name="detectorz", labels={"motors"})  # DetectorZ
fakemotor = EpicsMotor("BL6013:FakeMotor", name="fakemotor", labels={"motors"})  # FakeMotor
g10x = EpicsMotor("BL0601:G10xAngle", name="g10x", labels={"motors"})  # G10x
gap = EpicsMotor("SR06U___GDS1PS_AM00", name="gap", labels={"motors"})  # Gap
gapreq = EpicsMotor("cmm:ID6_bl_input", name="gapreq", labels={"motors"})  # GapReq
gratingangle = EpicsMotor("BL6013:GratingAnglealpha", name="gratingangle", labels={"motors"})  # GratingAngle
m101pitch = EpicsMotor("BL0601:M101Pitch", name="m101pitch", labels={"motors"})  # M101Pitch
m101roll = EpicsMotor("BL0601:M101Roll", name="m101roll", labels={"motors"})  # M101Roll
m102 = EpicsMotor("BL0601:M102Angle", name="m102", labels={"motors"})  # M102
m131pitch = EpicsMotor("BL0601:M131Pitch", name="m131pitch", labels={"motors"})  # M131Pitch
m131roll = EpicsMotor("BL0601:M131Roll", name="m131roll", labels={"motors"})  # M131Roll
m132 = EpicsMotor("BL0601:M132Pitch", name="m132", labels={"motors"})  # M132
m133 = EpicsMotor("BL0601:M133Pitch", name="m133", labels={"motors"})  # M133
mainmanipx = EpicsMotor("BL6013:MainManipX", name="mainmanipx", labels={"motors"})  # MainManipX
mainmanipy = EpicsMotor("BL6013:MainManipY", name="mainmanipy", labels={"motors"})  # MainManipY
mainmanipz = EpicsMotor("BL6013:MainManipZ", name="mainmanipz", labels={"motors"})  # MainManipZ
mainmaniptheta = EpicsMotor("BL6013:MainManiptheta", name="mainmaniptheta", labels={"motors"})  # MainManiptheta
microscopex = EpicsMotor("BL6013:MicroscopeX", name="microscopex", labels={"motors"})  # MicroscopeX
microscopey = EpicsMotor("BL6013:MicroscopeY", name="microscopey", labels={"motors"})  # MicroscopeY
microscopez = EpicsMotor("BL6013:MicroscopeZ", name="microscopez", labels={"motors"})  # MicroscopeZ
mirrorangle = EpicsMotor("BL6013:MirrorAngle", name="mirrorangle", labels={"motors"})  # MirrorAngle
monoenergy = EpicsMotor("BL6013:MonoEnergyUDP", name="monoenergy", labels={"motors"})  # MonoEnergy
shtr131pzt = EpicsMotor("BL0601:SHTR131PZT", name="shtr131pzt", labels={"motors"})  # SHTR131PZT
shtr131pos = EpicsMotor("BL0601:SHTR131Pos", name="shtr131pos", labels={"motors"})  # SHTR131Pos
slit = EpicsMotor("BL6013:SLIT131VertSizeUDP", name="slit", labels={"motors"})  # SLIT
spectopticsheight = EpicsMotor("BL6013:SpectOpticsHeight", name="spectopticsheight", labels={"motors"})  # SpectOpticsHeight
spectopticspitch = EpicsMotor("BL6013:SpectOpticsPitch", name="spectopticspitch", labels={"motors"})  # SpectOpticsPitch
spectopticsroll = EpicsMotor("BL6013:SpectOpticsRoll", name="spectopticsroll", labels={"motors"})  # SpectOpticsRoll

# ── AI Signals (AveragedScalar — time-averaged over exposure_time) ──
# exposure_time is set at runtime by the plan wrappers in 15_plans.py.
# Default 1.0 s; the GUI passes the operator's chosen value per scan.
diag132diode = AveragedScalar("BL601:DIAG132Diode", name="diag132diode", labels={"detectors"})  # DIAG132Diode
diag132tey = AveragedScalar("BL601:DIAG132TEY", name="diag132tey", labels={"detectors"})  # DIAG132TEY
diode133 = AveragedScalar("6013E1608:Ai2", name="diode133", labels={"detectors"})  # Diode133
diode134 = AveragedScalar("6013E1608:Ai4", name="diode134", labels={"detectors"})  # Diode134
ig001 = AveragedScalar("FE06BL0:IG001:Analog:Torr", name="ig001", labels={"detectors"})  # IG001
ig002 = AveragedScalar("FE06BL0:IG002:Analog:Torr", name="ig002", labels={"detectors"})  # IG002
ig101 = AveragedScalar("FE06BL0:IG101:Analog:Torr", name="ig101", labels={"detectors"})  # IG101
ig102 = AveragedScalar("BL0601:IG102:Torr", name="ig102", labels={"detectors"})  # IG102
ig103 = AveragedScalar("BL0601:IG103:Torr", name="ig103", labels={"detectors"})  # IG103
ig104 = AveragedScalar("BL0601:IG104:Torr", name="ig104", labels={"detectors"})  # IG104
ig105 = AveragedScalar("BL0601:IG105:Torr", name="ig105", labels={"detectors"})  # IG105
ig131 = AveragedScalar("BL0601:IG131:Torr", name="ig131", labels={"detectors"})  # IG131
izero133 = AveragedScalar("6013E1608:Ai1", name="izero133", labels={"detectors"})  # Izero133
izero134 = AveragedScalar("6013E1608:Ai3", name="izero134", labels={"detectors"})  # Izero134
teydn = AveragedScalar("6013E1608:Ai6", name="teydn", labels={"detectors"})  # TEYdn
teyup = AveragedScalar("6013E1608:Ai5", name="teyup", labels={"detectors"})  # TEYup
tfychanneltron = AveragedScalar("6013E1608:Ai7", name="tfychanneltron", labels={"detectors"})  # TFYChanneltron
tfydiode = AveragedScalar("6013E1608:Ai8", name="tfydiode", labels={"detectors"})  # TFYDiode

# ── Area Detectors ──────────────────────────────────────────────────
# TODO: replace stubs with full areaDetector ophyd device classes
# that include the cam, image, stats plugins appropriate for each
# detector.  The device name must match the key in the map below.
# andor = <YourDetectorClass>('6013ANDOR:', name='andor')  # andor
# simdetector = <YourDetectorClass>('6013SIM1:', name='simdetector')  # simDetector

# ── Data storage setup ───────────────────────────────────────────────
# Output directories (created automatically):
#   ~/Data/              — per-scan HDF5 files  (h5py, no suitcase needed)
#   ~/bluesky/msgpack/   — bluesky document store (suitcase-msgpack)
#
# Required packages (install in the bluesky venv):
#   pip install event-model suitcase-msgpack
#   h5py is already required by the main qtui venv
#
import os
from pathlib import Path
from datetime import datetime as _dt

_EXPORT_DIR  = Path(os.environ.get("AMBER_DATA_DIR",
                                    str(Path.home() / "Data")))
_MSGPACK_DIR = Path.home() / "bluesky" / "msgpack"
_EXPORT_DIR.mkdir(parents=True, exist_ok=True)
_MSGPACK_DIR.mkdir(parents=True, exist_ok=True)

# In-session databroker catalog (temp — no mongo, no persistent store needed
# at the catalog level since we persist via msgpack + HDF5 below).
try:
    import databroker
    db = databroker.temp()
    RE.subscribe(db.insert)
    print("[startup] RE subscribed to in-session databroker catalog")
except Exception as _e:
    print(f"[startup] databroker unavailable: {_e}")
    db = None

# ── Per-scan msgpack serialisation (pip install suitcase-msgpack) ────
try:
    import suitcase.msgpack
    from event_model import RunRouter as _RunRouter

    def _msgpack_factory(name, doc):
        if name != "start":
            return [], []
        uid8 = doc.get("uid", "unknown")[:8]
        num  = doc.get("scan_id", 0)
        dts  = _dt.fromtimestamp(doc.get("time", 0)).strftime("%Y%m%dT%H%M%S")
        path = str(_MSGPACK_DIR / f"scan_{num:04d}_{uid8}_{dts}")
        print(f"[startup] msgpack → {path}.msgpack")
        return [suitcase.msgpack.Serializer(path)], []

    RE.subscribe(_RunRouter([_msgpack_factory]))
    print(f"[startup] msgpack serialisation active → {_MSGPACK_DIR}")

except ImportError:
    print("[startup] suitcase-msgpack not installed — "
          "run: pip install suitcase-msgpack")

# ── Per-scan HDF5 export (h5py + event-model, no suitcase needed) ────
try:
    import h5py as _h5py
    import numpy as _np
    from event_model import RunRouter

    class _HDF5Callback:
        """Accumulates bluesky documents for one run and writes an HDF5 file
        on stop.  One instance per run, created by _hdf5_factory.

        Compatible with event-model >= 1.14.0: RunRouter calls the callback
        directly as callback(name, doc), so __call__ dispatches to the
        appropriate method.
        """

        def __init__(self, path: str):
            self._path      = path
            self._start_doc = {}
            self._columns   = []
            self._data      = {}

        def __call__(self, name: str, doc: dict):
            """Dispatcher — event-model >= 1.14.0 calls callbacks this way."""
            getattr(self, name, lambda d: None)(doc)

        def start(self, doc):
            self._start_doc = doc

        def descriptor(self, doc):
            if self._columns:
                return  # use first descriptor only
            hints   = doc.get("hints", {})
            dims    = [d[0][0] for d in hints.get("dimensions", []) if d[0]]
            others  = [k for k in doc["data_keys"] if k not in dims]
            self._columns = dims + others
            self._data    = {k: [] for k in self._columns}

        def event(self, doc):
            data = doc.get("data", {})
            for k in self._columns:
                self._data[k].append(data.get(k, float("nan")))

        def event_page(self, doc):
            data = doc.get("data", {})
            n = len(next(iter(data.values()), []))
            for i in range(n):
                for k in self._columns:
                    col = data.get(k, [float("nan")] * n)
                    self._data[k].append(
                        col[i] if i < len(col) else float("nan"))

        def stop(self, doc):
            if not any(self._data.values()):
                print(f"[startup] HDF5: no data for {self._path}")
                return
            try:
                with _h5py.File(self._path, "w") as f:
                    meta = f.create_group("scan/metadata")
                    for k, v in self._start_doc.items():
                        try:
                            meta.attrs[k] = str(v)
                        except Exception:
                            pass
                    meta.attrs["file_format"] = "AMBER_HiRRIXS_HDF5_v1"
                    meta.attrs["beamline"]    = "ALS BL601 AMBER"
                    dgrp = f.create_group("scan/data")
                    for k, vals in self._data.items():
                        if vals:
                            dgrp.create_dataset(
                                k, data=_np.array(vals, dtype=float))
                print(f"[startup] HDF5 written → {self._path}")
            except Exception as exc:
                print(f"[startup] HDF5 error: {exc}")

    def _hdf5_factory(name, doc):
        if name != "start":
            return [], []
        uid8 = doc.get("uid", "unknown")[:8]
        num  = doc.get("scan_id", 0)
        dts  = _dt.fromtimestamp(doc.get("time", 0)).strftime("%Y%m%dT%H%M%S")
        # The GUI-supplied file path arrives at the top level of the start doc
        # (bluesky-queueserver flattens item meta into the start document).
        # Fall back to auto-generated ~/Data path for scans run outside the GUI.
        gui_path = doc.get("file", "")
        if gui_path:
            path = gui_path
            Path(path).parent.mkdir(parents=True, exist_ok=True)
        else:
            path = str(_EXPORT_DIR / f"scan_{num:04d}_{uid8}_{dts}.h5")
        print(f"[startup] HDF5 → {path}")
        return [_HDF5Callback(path)], []

    RE.subscribe(RunRouter([_hdf5_factory]))
    print(f"[startup] HDF5 export active → {_EXPORT_DIR}")

except ImportError as _imp_e:
    print(f"[startup] HDF5 export unavailable: {_imp_e}")
    print("[startup] Install with: pip install event-model h5py")

# ── Convenience aliases ─────────────────────────────────────────────
# Add any extra devices, callbacks, or subscriptions here.

from nxxas_writer import make_nxxas_factory
RE.subscribe(_RunRouter([make_nxxas_factory(_EXPORT_DIR)]))