"""
AMBER / HiRRIXS — bluesky RE Manager startup script.
Auto-generated by devices.py — edit as needed before production use.
"""
from ophyd import EpicsMotor, EpicsSignalRO, Device
from ophyd.sim import SynGauss, SynAxis
import bluesky.plans as bp
import bluesky.plan_stubs as bps

# ── Motors ──────────────────────────────────────────────────────────
ap131pos = EpicsMotor("BL0601:AP131Pos", name="ap131pos", labels={"motors"})  # AP131Pos
ap131size = EpicsMotor("BL0601:AP131Size", name="ap131size", labels={"motors"})  # AP131Size
ap132pos = EpicsMotor("BL0601:AP132Pos", name="ap132pos", labels={"motors"})  # AP132Pos
ap132size = EpicsMotor("BL0601:AP132Size", name="ap132size", labels={"motors"})  # AP132Size
beamlineenergy = EpicsMotor("BL6013:BeamlineEnergyUDP", name="beamlineenergy", labels={"motors"})  # BeamlineEnergy
diag101 = EpicsMotor("BL0601:DIAG101Pos", name="diag101", labels={"motors"})  # DIAG101
diag132 = EpicsMotor("BL0601:DIAG132Insert", name="diag132", labels={"motors"})  # DIAG132
diag133 = EpicsMotor("BL6013:DIAG133Insert", name="diag133", labels={"motors"})  # DIAG133
diag134 = EpicsMotor("BL6013:DIAG134Insert", name="diag134", labels={"motors"})  # DIAG134
detectorx = EpicsMotor("BL6013:DetectorX", name="detectorx", labels={"motors"})  # DetectorX
detectorz = EpicsMotor("BL6013:DetectorZ", name="detectorz", labels={"motors"})  # DetectorZ
fakemotor = EpicsMotor("BL6013:FakeMotor", name="fakemotor", labels={"motors"})  # FakeMotor
g10x = EpicsMotor("BL0601:G10xAngle", name="g10x", labels={"motors"})  # G10x
gap = EpicsMotor("SR06U___GDS1PS_AM00", name="gap", labels={"motors"})  # Gap
gapreq = EpicsMotor("cmm:ID6_bl_input", name="gapreq", labels={"motors"})  # GapReq
gratingangle = EpicsMotor("BL6013:GratingAnglealpha", name="gratingangle", labels={"motors"})  # GratingAngle
m101pitch = EpicsMotor("BL0601:M101Pitch", name="m101pitch", labels={"motors"})  # M101Pitch
m101roll = EpicsMotor("BL0601:M101Roll", name="m101roll", labels={"motors"})  # M101Roll
m102 = EpicsMotor("BL0601:M102Angle", name="m102", labels={"motors"})  # M102
m131pitch = EpicsMotor("BL0601:M131Pitch", name="m131pitch", labels={"motors"})  # M131Pitch
m131roll = EpicsMotor("BL0601:M131Roll", name="m131roll", labels={"motors"})  # M131Roll
m132 = EpicsMotor("BL0601:M132Pitch", name="m132", labels={"motors"})  # M132
m133 = EpicsMotor("BL0601:M133Pitch", name="m133", labels={"motors"})  # M133
mainmanipx = EpicsMotor("BL6013:MainManipX", name="mainmanipx", labels={"motors"})  # MainManipX
mainmanipy = EpicsMotor("BL6013:MainManipY", name="mainmanipy", labels={"motors"})  # MainManipY
mainmanipz = EpicsMotor("BL6013:MainManipZ", name="mainmanipz", labels={"motors"})  # MainManipZ
mainmaniptheta = EpicsMotor("BL6013:MainManiptheta", name="mainmaniptheta", labels={"motors"})  # MainManiptheta
microscopex = EpicsMotor("BL6013:MicroscopeX", name="microscopex", labels={"motors"})  # MicroscopeX
microscopey = EpicsMotor("BL6013:MicroscopeY", name="microscopey", labels={"motors"})  # MicroscopeY
microscopez = EpicsMotor("BL6013:MicroscopeZ", name="microscopez", labels={"motors"})  # MicroscopeZ
mirrorangle = EpicsMotor("BL6013:MirrorAngle", name="mirrorangle", labels={"motors"})  # MirrorAngle
monoenergy = EpicsMotor("BL6013:MonoEnergyUDP", name="monoenergy", labels={"motors"})  # MonoEnergy
shtr131pzt = EpicsMotor("BL0601:SHTR131PZT", name="shtr131pzt", labels={"motors"})  # SHTR131PZT
shtr131pos = EpicsMotor("BL0601:SHTR131Pos", name="shtr131pos", labels={"motors"})  # SHTR131Pos
slit = EpicsMotor("BL6013:SLIT131VertSizeUDP", name="slit", labels={"motors"})  # SLIT
spectopticsheight = EpicsMotor("BL6013:SpectOpticsHeight", name="spectopticsheight", labels={"motors"})  # SpectOpticsHeight
spectopticspitch = EpicsMotor("BL6013:SpectOpticsPitch", name="spectopticspitch", labels={"motors"})  # SpectOpticsPitch
spectopticsroll = EpicsMotor("BL6013:SpectOpticsRoll", name="spectopticsroll", labels={"motors"})  # SpectOpticsRoll

# ── AI Signals ──────────────────────────────────────────────────────
diag132diode = EpicsSignalRO("BL601:DIAG132Diode", name="diag132diode", labels={"detectors"})  # DIAG132Diode
diag132tey = EpicsSignalRO("BL601:DIAG132TEY", name="diag132tey", labels={"detectors"})  # DIAG132TEY
diode133 = EpicsSignalRO("6013E1608:Ai2", name="diode133", labels={"detectors"})  # Diode133
diode134 = EpicsSignalRO("6013E1608:Ai4", name="diode134", labels={"detectors"})  # Diode134
ig001 = EpicsSignalRO("FE06BL0:IG001:Analog:Torr", name="ig001", labels={"detectors"})  # IG001
ig002 = EpicsSignalRO("FE06BL0:IG002:Analog:Torr", name="ig002", labels={"detectors"})  # IG002
ig101 = EpicsSignalRO("FE06BL0:IG101:Analog:Torr", name="ig101", labels={"detectors"})  # IG101
ig102 = EpicsSignalRO("BL0601:IG102:Torr", name="ig102", labels={"detectors"})  # IG102
ig103 = EpicsSignalRO("BL0601:IG103:Torr", name="ig103", labels={"detectors"})  # IG103
ig104 = EpicsSignalRO("BL0601:IG104:Torr", name="ig104", labels={"detectors"})  # IG104
ig105 = EpicsSignalRO("BL0601:IG105:Torr", name="ig105", labels={"detectors"})  # IG105
ig131 = EpicsSignalRO("BL0601:IG131:Torr", name="ig131", labels={"detectors"})  # IG131
izero133 = EpicsSignalRO("6013E1608:Ai1", name="izero133", labels={"detectors"})  # Izero133
izero134 = EpicsSignalRO("6013E1608:Ai3", name="izero134", labels={"detectors"})  # Izero134
teydn = EpicsSignalRO("6013E1608:Ai6", name="teydn", labels={"detectors"})  # TEYdn
teyup = EpicsSignalRO("6013E1608:Ai5", name="teyup", labels={"detectors"})  # TEYup
tfychanneltron = EpicsSignalRO("6013E1608:Ai7", name="tfychanneltron", labels={"detectors"})  # TFYChanneltron
tfydiode = EpicsSignalRO("6013E1608:Ai8", name="tfydiode", labels={"detectors"})  # TFYDiode

# ── Area Detectors ──────────────────────────────────────────────────
# TODO: replace stubs with full areaDetector ophyd device classes
# that include the cam, image, stats plugins appropriate for each
# detector.  The device name must match the key in the map below.
# andor = <YourDetectorClass>('6013ANDOR:', name='andor')  # andor
# simdetector = <YourDetectorClass>('6013SIM1:', name='simdetector')  # simDetector

# ── Convenience aliases ─────────────────────────────────────────────
# Add any extra devices, callbacks, or subscriptions here.

