"""
devices.py — Canonical ophyd device name mapping for AMBER / HiRRIXS.

The bluesky queue server worker resolves plan arguments (motors, detectors)
by name against its startup namespace.  This module provides:

  device_name(friendly)        → str   Python-safe ophyd identifier
  motor_device_map(cfg)        → dict  {friendly_name: device_name}
  signal_device_map(cfg)       → dict  {friendly_name: device_name}
  area_det_device_map(cfg)     → dict  {friendly_name: device_name}
  all_device_map(amber, hirr)  → dict  {friendly_name: device_name}
  write_startup_script(path, amber_cfg, hirrixs_cfg)
                               → None  writes a bluesky startup .py file

The startup script is what the RE Manager worker loads on environment open.
It must use the same device names this module produces so that plan args
submitted from the GUI resolve correctly in the worker namespace.
"""

import re
from pathlib import Path


# ── Name canonicalisation ─────────────────────────────────────────────────────

def device_name(friendly: str) -> str:
    """Convert a friendly config key to a valid Python / ophyd identifier.

    Examples
    --------
    "MainManipX"     → "mainmanipx"
    "TEYup"          → "teyup"
    "Izero133"       → "izero133"
    "M102"           → "m102"
    "simDetector"    → "simdetector"
    """
    # Replace any non-alphanumeric chars with underscore, lowercase
    s = re.sub(r"[^a-zA-Z0-9]", "_", friendly).lower()
    # Strip leading digits / underscores so it's always a valid identifier
    s = re.sub(r"^[^a-zA-Z]+", "", s) or "dev_" + s
    return s


# ── Per-section maps ──────────────────────────────────────────────────────────

def _flatten_motors(motor_section: dict) -> dict[str, str]:
    """Return {friendly_name: pv_string} handling both plain-string and
    sub-dict motor entries."""
    out: dict[str, str] = {}
    for k, v in motor_section.items():
        if isinstance(v, str):
            out[k] = v
        elif isinstance(v, dict):
            for sk, sv in v.items():
                if isinstance(sv, str):
                    # sub-key already has the full PV; use the sub-key as name
                    out[sk] = sv
    return out


def motor_device_map(amber_cfg: dict, hirrixs_cfg: dict) -> dict[str, str]:
    """Return {friendly_name: device_name} for all motors."""
    motors: dict[str, str] = {}
    for cfg in (amber_cfg, hirrixs_cfg):
        for fname in _flatten_motors(cfg.get("motor", {})):
            motors[fname] = device_name(fname)
    return motors


def signal_device_map(amber_cfg: dict, hirrixs_cfg: dict) -> dict[str, str]:
    """Return {friendly_name: device_name} for all AI signals."""
    signals: dict[str, str] = {}
    for cfg in (amber_cfg, hirrixs_cfg):
        for fname in cfg.get("signal", {}):
            signals[fname] = device_name(fname)
    return signals


def area_det_device_map(hirrixs_cfg: dict) -> dict[str, str]:
    """Return {friendly_name: device_name} for area detectors."""
    return {fname: device_name(fname)
            for fname in hirrixs_cfg.get("detector", {})}


def all_device_map(amber_cfg: dict, hirrixs_cfg: dict) -> dict[str, str]:
    """Union of all three maps — used by DAQTab to look up device names."""
    d = motor_device_map(amber_cfg, hirrixs_cfg)
    d.update(signal_device_map(amber_cfg, hirrixs_cfg))
    d.update(area_det_device_map(hirrixs_cfg))
    return d


# ── Startup script generator ──────────────────────────────────────────────────

def write_startup_script(path: "str | Path",
                         amber_cfg: dict,
                         hirrixs_cfg: dict) -> None:
    """Write a bluesky RE Manager startup script to *path*.

    The generated file instantiates:
      - EpicsMotor for every motor
      - EpicsSignalRO for every AI signal
      - SimDetector / EpicsAreaDetector stubs for area detectors
      - A best-effort EpicsScaler or SynGauss for quick testing

    Edit the generated file to add ophyd area-detector plugin chains,
    custom staging, etc. before deploying to production.
    """
    lines = [
        '"""',
        "AMBER / HiRRIXS — bluesky RE Manager startup script.",
        "Auto-generated by devices.py — edit as needed before production use.",
        '"""',
        "from ophyd import EpicsMotor, EpicsSignalRO, Device",
        "from ophyd.sim import SynGauss, SynAxis",
        "import bluesky.plans as bp",
        "import bluesky.plan_stubs as bps",
        "",
        "# ── Motors ──────────────────────────────────────────────────────────",
    ]

    all_motors = _flatten_motors(amber_cfg.get("motor", {}))
    all_motors.update(_flatten_motors(hirrixs_cfg.get("motor", {})))
    for fname, pv in sorted(all_motors.items()):
        dname = device_name(fname)
        lines.append(
            f'{dname} = EpicsMotor("{pv}", name="{dname}", '
            f'labels={{"motors"}})  # {fname}')

    lines += [
        "",
        "# ── AI Signals ──────────────────────────────────────────────────────",
    ]
    all_signals: dict[str, str] = {}
    for cfg in (amber_cfg, hirrixs_cfg):
        all_signals.update(cfg.get("signal", {}))
    for fname, pv in sorted(all_signals.items()):
        dname = device_name(fname)
        lines.append(
            f'{dname} = EpicsSignalRO("{pv}", name="{dname}", '
            f'labels={{"detectors"}})  # {fname}')

    lines += [
        "",
        "# ── Area Detectors ──────────────────────────────────────────────────",
        "# TODO: replace stubs with full areaDetector ophyd device classes",
        "# that include the cam, image, stats plugins appropriate for each",
        "# detector.  The device name must match the key in the map below.",
    ]
    for fname, pv in sorted(hirrixs_cfg.get("detector", {}).items()):
        dname = device_name(fname)
        lines.append(
            f"# {dname} = <YourDetectorClass>('{pv}:', name='{dname}')  "
            f"# {fname}")

    lines += [
        "",
        "# ── Convenience aliases ─────────────────────────────────────────────",
        "# Add any extra devices, callbacks, or subscriptions here.",
        "",
    ]

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[devices.py] Startup script written to {path}")


# ── CLI helper ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent))
    from common import load_json

    base        = Path(__file__).parent.parent / "config"
    amber_cfg   = load_json(base / "amber.json").get("amber", {})
    hirrixs_cfg = load_json(base / "hirrixs.json").get("hirrixs", {})
    out         = base / "bluesky_startup.py"
    write_startup_script(out, amber_cfg, hirrixs_cfg)
    print("Device map:")
    for k, v in all_device_map(amber_cfg, hirrixs_cfg).items():
        print(f"  {k:30s} → {v}")
